/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DriveSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/auth.ts
var import_obsidian = require("obsidian");
var DRIVE_SCOPE = "https://www.googleapis.com/auth/drive.file";
var AUTH_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth";
var TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token";
function base64UrlEncode(bytes) {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function randomUrlSafeString(byteLength) {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  return base64UrlEncode(bytes);
}
async function pkceChallenge(verifier) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier));
  return base64UrlEncode(new Uint8Array(digest));
}
async function tokenRequest(params) {
  var _a, _b;
  const resp = await fetch(TOKEN_ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(params).toString()
  });
  const json = await resp.json();
  if (!resp.ok || json.error) {
    throw new Error(`Token request failed: ${(_a = json.error) != null ? _a : resp.status} ${(_b = json.error_description) != null ? _b : ""}`);
  }
  return json;
}
async function authenticate(config) {
  if (!import_obsidian.Platform.isDesktopApp) {
    throw new Error(
      "Sign-in must be done on desktop. Connect there, then use \u201CExport auth\u201D / \u201CImport auth\u201D in settings to bring the connection to this device."
    );
  }
  if (!config.clientId || !config.clientSecret) {
    throw new Error("Set your Google OAuth Client ID and Client Secret in the plugin settings first (see README).");
  }
  const http = require("http");
  const verifier = randomUrlSafeString(48);
  const challenge = await pkceChallenge(verifier);
  const expectedState = randomUrlSafeString(16);
  return new Promise((resolve, reject) => {
    const server = http.createServer(async (req, res) => {
      var _a;
      try {
        const url = new URL((_a = req.url) != null ? _a : "/", "http://127.0.0.1");
        if (url.pathname !== "/callback") {
          res.writeHead(404).end();
          return;
        }
        const code = url.searchParams.get("code");
        const state = url.searchParams.get("state");
        const err = url.searchParams.get("error");
        res.writeHead(200, { "Content-Type": "text/html" });
        if (err || !code || state !== expectedState) {
          res.end("<h3>Sign-in failed. You can close this window and try again in Obsidian.</h3>");
          finish(new Error(err != null ? err : "No authorization code returned"));
          return;
        }
        res.end("<h3>Connected to Google Drive. You can close this window and return to Obsidian.</h3>");
        const address = server.address();
        const port = typeof address === "object" && address ? address.port : 0;
        const token = await tokenRequest({
          code,
          client_id: config.clientId,
          client_secret: config.clientSecret,
          redirect_uri: `http://127.0.0.1:${port}/callback`,
          grant_type: "authorization_code",
          code_verifier: verifier
        });
        if (!token.refresh_token) {
          finish(new Error("Google did not return a refresh token. Remove the app's access at myaccount.google.com/permissions and connect again."));
          return;
        }
        finish(null, {
          accessToken: token.access_token,
          refreshToken: token.refresh_token,
          expiresAt: Date.now() + token.expires_in * 1e3
        });
      } catch (e) {
        finish(e instanceof Error ? e : new Error(String(e)));
      }
    });
    const timeout = setTimeout(() => {
      finish(new Error("Timed out waiting for Google sign-in (5 minutes)."));
    }, 5 * 60 * 1e3);
    let done = false;
    function finish(error, tokens) {
      if (done) return;
      done = true;
      clearTimeout(timeout);
      server.close();
      if (error) reject(error);
      else resolve(tokens);
    }
    server.on("error", (e) => finish(e));
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      const port = typeof address === "object" && address ? address.port : 0;
      const params = new URLSearchParams({
        client_id: config.clientId,
        redirect_uri: `http://127.0.0.1:${port}/callback`,
        response_type: "code",
        scope: DRIVE_SCOPE,
        access_type: "offline",
        prompt: "consent",
        state: expectedState,
        code_challenge: challenge,
        code_challenge_method: "S256"
      });
      const authUrl = `${AUTH_ENDPOINT}?${params.toString()}`;
      window.open(authUrl);
      new import_obsidian.Notice("Complete the Google sign-in in your browser\u2026");
    });
  });
}
async function ensureFreshTokens(config, tokens) {
  var _a;
  if (Date.now() < tokens.expiresAt - 6e4) return tokens;
  const resp = await tokenRequest({
    client_id: config.clientId,
    client_secret: config.clientSecret,
    refresh_token: tokens.refreshToken,
    grant_type: "refresh_token"
  });
  return {
    accessToken: resp.access_token,
    refreshToken: (_a = resp.refresh_token) != null ? _a : tokens.refreshToken,
    expiresAt: Date.now() + resp.expires_in * 1e3
  };
}

// src/crypto.ts
var MAGIC = new Uint8Array([79, 68, 83, 49, 0]);
var IV_LENGTH = 12;
var PBKDF2_ITERATIONS = 31e4;
function hasEncryptionMagic(data) {
  if (data.byteLength < MAGIC.length) return false;
  const head = new Uint8Array(data, 0, MAGIC.length);
  return MAGIC.every((b, i) => head[i] === b);
}
var plaintextCodec = {
  active: false,
  async encode(data) {
    return data;
  },
  async decode(data) {
    if (hasEncryptionMagic(data)) {
      throw new Error(
        "This file is encrypted on Drive. Set the encryption password in the Google Drive Sync settings."
      );
    }
    return data;
  }
};
function generateSaltB64() {
  const salt = new Uint8Array(16);
  crypto.getRandomValues(salt);
  let binary = "";
  for (const b of salt) binary += String.fromCharCode(b);
  return btoa(binary);
}
function b64ToBytes(b64) {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
async function createEncryptionCodec(password, saltB64) {
  const baseKey = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, [
    "deriveKey"
  ]);
  const salt = b64ToBytes(saltB64);
  const key = await crypto.subtle.deriveKey(
    { name: "PBKDF2", salt: salt.buffer, iterations: PBKDF2_ITERATIONS, hash: "SHA-256" },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"]
  );
  return {
    active: true,
    async encode(data) {
      const iv = new Uint8Array(IV_LENGTH);
      crypto.getRandomValues(iv);
      const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, data);
      const out = new Uint8Array(MAGIC.length + IV_LENGTH + ciphertext.byteLength);
      out.set(MAGIC, 0);
      out.set(iv, MAGIC.length);
      out.set(new Uint8Array(ciphertext), MAGIC.length + IV_LENGTH);
      return out.buffer;
    },
    async decode(data) {
      if (!hasEncryptionMagic(data)) return data;
      const iv = new Uint8Array(data, MAGIC.length, IV_LENGTH);
      const ciphertext = data.slice(MAGIC.length + IV_LENGTH);
      try {
        return await crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, ciphertext);
      } catch (e) {
        throw new Error("Decryption failed \u2014 the encryption password doesn't match the one used to upload.");
      }
    }
  };
}

// src/driveClient.ts
var import_obsidian2 = require("obsidian");
var API = "https://www.googleapis.com/drive/v3";
var UPLOAD_API = "https://www.googleapis.com/upload/drive/v3";
var FOLDER_MIME = "application/vnd.google-apps.folder";
var DriveClient = class {
  constructor(getAccessToken) {
    this.getAccessToken = getAccessToken;
  }
  async request(params) {
    var _a, _b, _c, _d, _e;
    let token = await this.getAccessToken(false);
    for (let attempt = 0; ; attempt++) {
      const resp = await (0, import_obsidian2.requestUrl)({
        url: params.url,
        method: (_a = params.method) != null ? _a : "GET",
        body: params.body,
        contentType: params.contentType,
        headers: { Authorization: `Bearer ${token}` },
        throw: false
      });
      if (resp.status === 401 && attempt === 0) {
        token = await this.getAccessToken(true);
        continue;
      }
      if ((resp.status === 429 || resp.status >= 500) && attempt < 2) {
        await new Promise((r) => setTimeout(r, 1500 * (attempt + 1)));
        continue;
      }
      if (resp.status >= 400) {
        let detail = "";
        try {
          detail = (_d = (_c = (_b = resp.json) == null ? void 0 : _b.error) == null ? void 0 : _c.message) != null ? _d : resp.text.slice(0, 300);
        } catch (e) {
        }
        throw new Error(`Drive API ${resp.status} on ${(_e = params.method) != null ? _e : "GET"} ${params.url.split("?")[0]}: ${detail}`);
      }
      return resp;
    }
  }
  async getAccountEmail() {
    var _a, _b, _c;
    const resp = await this.request({ url: `${API}/about?fields=user(emailAddress)` });
    return (_c = (_b = (_a = resp.json) == null ? void 0 : _a.user) == null ? void 0 : _b.emailAddress) != null ? _c : "unknown";
  }
  async listChildren(folderId) {
    var _a;
    const out = [];
    let pageToken;
    do {
      const params = new URLSearchParams({
        q: `'${folderId}' in parents and trashed = false`,
        fields: "nextPageToken, files(id, name, mimeType, md5Checksum, modifiedTime, size)",
        pageSize: "1000"
      });
      if (pageToken) params.set("pageToken", pageToken);
      const resp = await this.request({ url: `${API}/files?${params.toString()}` });
      out.push(...(_a = resp.json.files) != null ? _a : []);
      pageToken = resp.json.nextPageToken;
    } while (pageToken);
    return out;
  }
  /** Finds (or creates) the vault's base folder at the root of My Drive. */
  async ensureBaseFolder(name, cachedId) {
    var _a;
    if (cachedId) {
      const resp = await (0, import_obsidian2.requestUrl)({
        url: `${API}/files/${cachedId}?fields=id,trashed`,
        headers: { Authorization: `Bearer ${await this.getAccessToken(false)}` },
        throw: false
      });
      if (resp.status === 200 && !resp.json.trashed) return cachedId;
    }
    const escaped = name.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
    const q = new URLSearchParams({
      q: `name = '${escaped}' and mimeType = '${FOLDER_MIME}' and 'root' in parents and trashed = false`,
      fields: "files(id)"
    });
    const found = await this.request({ url: `${API}/files?${q.toString()}` });
    if ((_a = found.json.files) == null ? void 0 : _a.length) return found.json.files[0].id;
    const created = await this.request({
      url: `${API}/files?fields=id`,
      method: "POST",
      contentType: "application/json",
      body: JSON.stringify({ name, mimeType: FOLDER_MIME })
    });
    return created.json.id;
  }
  /** Walks the base folder tree and returns every synced file and folder id. */
  async listTree(baseFolderId) {
    const files = /* @__PURE__ */ new Map();
    const folders = /* @__PURE__ */ new Map([["", baseFolderId]]);
    const queue = [{ id: baseFolderId, path: "" }];
    while (queue.length) {
      const { id, path } = queue.shift();
      for (const child of await this.listChildren(id)) {
        const childPath = path ? `${path}/${child.name}` : child.name;
        if (child.mimeType === FOLDER_MIME) {
          folders.set(childPath, child.id);
          queue.push({ id: child.id, path: childPath });
        } else if (child.md5Checksum) {
          files.set(childPath, {
            id: child.id,
            path: childPath,
            md5: child.md5Checksum,
            modifiedTime: child.modifiedTime ? Date.parse(child.modifiedTime) : 0,
            size: child.size ? parseInt(child.size, 10) : 0
          });
        }
      }
    }
    return { files, folders };
  }
  /** Creates any missing folders along dirPath and returns the deepest id. */
  async ensureFolderPath(dirPath, folders) {
    if (!dirPath) return folders.get("");
    const known = folders.get(dirPath);
    if (known) return known;
    const parentPath = dirPath.includes("/") ? dirPath.slice(0, dirPath.lastIndexOf("/")) : "";
    const parentId = await this.ensureFolderPath(parentPath, folders);
    const name = dirPath.slice(dirPath.lastIndexOf("/") + 1);
    const created = await this.request({
      url: `${API}/files?fields=id`,
      method: "POST",
      contentType: "application/json",
      body: JSON.stringify({ name, mimeType: FOLDER_MIME, parents: [parentId] })
    });
    folders.set(dirPath, created.json.id);
    return created.json.id;
  }
  async download(fileId) {
    const resp = await this.request({ url: `${API}/files/${fileId}?alt=media` });
    return resp.arrayBuffer;
  }
  /** Current cursor for the Changes API; changes after this point are listable. */
  async getStartPageToken() {
    const resp = await this.request({ url: `${API}/changes/startPageToken` });
    return resp.json.startPageToken;
  }
  /** All changes since the given cursor, plus the cursor for next time. */
  async listChanges(pageToken) {
    var _a;
    const changes = [];
    let token = pageToken;
    let newStartPageToken = pageToken;
    for (; ; ) {
      const params = new URLSearchParams({
        pageToken: token,
        pageSize: "1000",
        restrictToMyDrive: "true",
        fields: "nextPageToken, newStartPageToken, changes(fileId, removed, file(id, name, mimeType, md5Checksum, modifiedTime, size, parents, trashed))"
      });
      const resp = await this.request({ url: `${API}/changes?${params.toString()}` });
      changes.push(...(_a = resp.json.changes) != null ? _a : []);
      if (resp.json.newStartPageToken) newStartPageToken = resp.json.newStartPageToken;
      if (!resp.json.nextPageToken) break;
      token = resp.json.nextPageToken;
    }
    return { changes, newStartPageToken };
  }
  async getParents(fileId) {
    var _a;
    const resp = await this.request({ url: `${API}/files/${fileId}?fields=parents` });
    return (_a = resp.json.parents) != null ? _a : [];
  }
  /** Renames and/or moves a file — metadata only, preserves revision history. */
  async move(fileId, newName, addParentId, removeParentIds) {
    const params = new URLSearchParams({ fields: "id" });
    const removals = removeParentIds.filter((p) => p !== addParentId);
    if (removals.length) {
      params.set("addParents", addParentId);
      params.set("removeParents", removals.join(","));
    }
    await this.request({
      url: `${API}/files/${fileId}?${params.toString()}`,
      method: "PATCH",
      contentType: "application/json",
      body: JSON.stringify({ name: newName })
    });
  }
  /** Finds a file by exact name directly inside the given folder. */
  async findByName(name, parentId) {
    var _a;
    const escaped = name.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
    const params = new URLSearchParams({
      q: `name = '${escaped}' and '${parentId}' in parents and trashed = false`,
      fields: "files(id)"
    });
    const resp = await this.request({ url: `${API}/files?${params.toString()}` });
    return ((_a = resp.json.files) == null ? void 0 : _a.length) ? { id: resp.json.files[0].id } : null;
  }
  async listRevisionMeta(fileId) {
    var _a, _b;
    const out = [];
    let pageToken;
    do {
      const params = new URLSearchParams({
        fields: "nextPageToken, revisions(id, modifiedTime, size)",
        pageSize: "200"
      });
      if (pageToken) params.set("pageToken", pageToken);
      const resp = await this.request({ url: `${API}/files/${fileId}/revisions?${params.toString()}` });
      for (const rev of (_a = resp.json.revisions) != null ? _a : []) {
        out.push({ id: rev.id, modifiedTime: rev.modifiedTime, size: parseInt((_b = rev.size) != null ? _b : "0", 10) });
      }
      pageToken = resp.json.nextPageToken;
    } while (pageToken);
    return out;
  }
  /**
   * Finds the revision whose content matches the given md5 — used to recover
   * the common ancestor for three-way merges. Drive keeps revisions of
   * app-created files for ~30 days, so this can return null for old bases.
   */
  async findRevisionByMd5(fileId, md5) {
    var _a;
    let pageToken;
    do {
      const params = new URLSearchParams({
        fields: "nextPageToken, revisions(id, md5Checksum)",
        pageSize: "200"
      });
      if (pageToken) params.set("pageToken", pageToken);
      const resp = await this.request({ url: `${API}/files/${fileId}/revisions?${params.toString()}` });
      for (const rev of (_a = resp.json.revisions) != null ? _a : []) {
        if (rev.md5Checksum === md5) return rev.id;
      }
      pageToken = resp.json.nextPageToken;
    } while (pageToken);
    return null;
  }
  async downloadRevision(fileId, revisionId) {
    const resp = await this.request({ url: `${API}/files/${fileId}/revisions/${revisionId}?alt=media` });
    return resp.arrayBuffer;
  }
  async uploadNew(name, parentId, data) {
    const boundary = "obsidian_drive_sync_boundary";
    const metadata = JSON.stringify({ name, parents: [parentId] });
    const head = new TextEncoder().encode(
      `--${boundary}\r
Content-Type: application/json; charset=UTF-8\r
\r
${metadata}\r
--${boundary}\r
Content-Type: application/octet-stream\r
\r
`
    );
    const tail = new TextEncoder().encode(`\r
--${boundary}--`);
    const body = new Uint8Array(head.byteLength + data.byteLength + tail.byteLength);
    body.set(head, 0);
    body.set(new Uint8Array(data), head.byteLength);
    body.set(tail, head.byteLength + data.byteLength);
    const resp = await this.request({
      url: `${UPLOAD_API}/files?uploadType=multipart&fields=id,md5Checksum`,
      method: "POST",
      contentType: `multipart/related; boundary=${boundary}`,
      body: body.buffer
    });
    return { id: resp.json.id, md5: resp.json.md5Checksum };
  }
  async uploadUpdate(fileId, data) {
    const resp = await this.request({
      url: `${UPLOAD_API}/files/${fileId}?uploadType=media&fields=md5Checksum`,
      method: "PATCH",
      contentType: "application/octet-stream",
      body: data
    });
    return { md5: resp.json.md5Checksum };
  }
  /** Moves a file to the Drive trash (recoverable for 30 days). */
  async trash(fileId) {
    await this.request({
      url: `${API}/files/${fileId}`,
      method: "PATCH",
      contentType: "application/json",
      body: JSON.stringify({ trashed: true })
    });
  }
};

// src/logger.ts
var _SyncLog = class _SyncLog {
  constructor() {
    this.entries = [];
  }
  add(message) {
    const time = (/* @__PURE__ */ new Date()).toLocaleTimeString();
    this.entries.push(`[${time}] ${message}`);
    if (this.entries.length > _SyncLog.MAX_ENTRIES) {
      this.entries.splice(0, this.entries.length - _SyncLog.MAX_ENTRIES);
    }
  }
  get text() {
    return this.entries.length ? this.entries.join("\n") : "No sync activity yet.";
  }
  clear() {
    this.entries = [];
  }
};
_SyncLog.MAX_ENTRIES = 1e3;
var SyncLog = _SyncLog;

// src/modals.ts
var import_obsidian3 = require("obsidian");
var ConfirmModal = class _ConfirmModal extends import_obsidian3.Modal {
  constructor(app, title, body, ctaText, resolve) {
    super(app);
    this.title = title;
    this.body = body;
    this.ctaText = ctaText;
    this.resolve = resolve;
    this.resolved = false;
  }
  static ask(app, title, body, ctaText) {
    return new Promise((resolve) => new _ConfirmModal(app, title, body, ctaText, resolve).open());
  }
  onOpen() {
    this.titleEl.setText(this.title);
    for (const line of this.body) this.contentEl.createEl("p", { text: line });
    new import_obsidian3.Setting(this.contentEl).addButton(
      (b) => b.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton(
      (b) => b.setButtonText(this.ctaText).setWarning().onClick(() => {
        this.resolved = true;
        this.resolve(true);
        this.close();
      })
    );
  }
  onClose() {
    if (!this.resolved) this.resolve(false);
    this.contentEl.empty();
  }
};
var ACTION_LABELS = {
  "upload-new": "Upload (new)",
  "upload-update": "Upload (changed)",
  download: "Download",
  "delete-local": "Delete locally",
  "delete-remote": "Delete on Drive",
  conflict: "Conflict to resolve",
  inspect: "Compare (new on both sides)",
  "rename-remote": "Rename on Drive",
  "rename-local": "Rename locally",
  "refresh-id": "Refresh metadata",
  forget: "Forget stale entry"
};
var DryRunModal = class extends import_obsidian3.Modal {
  constructor(app, plan) {
    super(app);
    this.plan = plan;
  }
  onOpen() {
    var _a, _b;
    this.titleEl.setText("Sync preview");
    const { actions, unchanged } = this.plan;
    if (actions.length === 0) {
      this.contentEl.createEl("p", { text: `Nothing to do \u2014 ${unchanged} file(s) already in sync.` });
      return;
    }
    this.contentEl.createEl("p", {
      text: `${actions.length} action(s) pending, ${unchanged} file(s) unchanged. Nothing has been executed.`
    });
    const groups = /* @__PURE__ */ new Map();
    for (const a of actions) {
      const label = ACTION_LABELS[a.type];
      const desc = a.type === "rename-remote" || a.type === "rename-local" ? `${a.from} \u2192 ${a.to}` : a.path;
      (_b = (_a = groups.get(label)) != null ? _a : groups.set(label, []).get(label)) == null ? void 0 : _b.push(desc);
    }
    for (const [label, paths] of groups) {
      this.contentEl.createEl("h5", { text: `${label} (${paths.length})` });
      const list = this.contentEl.createEl("ul");
      for (const p of paths.slice(0, 50)) list.createEl("li", { text: p });
      if (paths.length > 50) list.createEl("li", { text: `\u2026and ${paths.length - 50} more` });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var HistoryModal = class extends import_obsidian3.Modal {
  constructor(app, filePath, revisions, restore) {
    super(app);
    this.filePath = filePath;
    this.revisions = revisions;
    this.restore = restore;
  }
  onOpen() {
    this.titleEl.setText(`Version history \u2014 ${this.filePath}`);
    if (this.revisions.length === 0) {
      this.contentEl.createEl("p", { text: "No revisions found on Drive for this file." });
      return;
    }
    this.contentEl.createEl("p", {
      text: "Versions stored on Google Drive (kept ~30 days). Restoring overwrites the local file; the restored version uploads on the next sync."
    });
    for (const rev of [...this.revisions].reverse()) {
      const row = new import_obsidian3.Setting(this.contentEl).setName(new Date(rev.modifiedTime).toLocaleString()).setDesc(`${(rev.size / 1024).toFixed(1)} KB`);
      row.addButton(
        (b) => b.setButtonText("Restore").onClick(async () => {
          b.setDisabled(true);
          try {
            await this.restore(rev.id);
            new import_obsidian3.Notice(`Restored ${this.filePath} to the version from ${new Date(rev.modifiedTime).toLocaleString()}`);
            this.close();
          } catch (e) {
            new import_obsidian3.Notice(`Restore failed: ${e instanceof Error ? e.message : e}`);
            b.setDisabled(false);
          }
        })
      );
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var LogModal = class extends import_obsidian3.Modal {
  constructor(app, text) {
    super(app);
    this.text = text;
  }
  onOpen() {
    this.titleEl.setText("Sync log");
    const pre = this.contentEl.createEl("pre", { text: this.text });
    pre.style.maxHeight = "60vh";
    pre.style.overflow = "auto";
    pre.style.whiteSpace = "pre-wrap";
    pre.style.userSelect = "text";
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var DriveSyncSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Google account").setHeading();
    const connected = !!this.plugin.data.tokens;
    new import_obsidian4.Setting(containerEl).setName(connected ? "Connected" : "Not connected").setDesc(
      connected ? "Sync is authorized. Disconnect to sign out or switch accounts." : "Create an OAuth client (Desktop app) in Google Cloud Console, paste its ID and secret below, then connect. See the README for a step-by-step guide."
    ).addButton(
      (btn) => btn.setButtonText(connected ? "Disconnect" : "Connect to Google Drive").setCta().onClick(async () => {
        if (connected) {
          this.plugin.data.tokens = null;
          await this.plugin.savePluginData();
          new import_obsidian4.Notice("Disconnected from Google Drive.");
          this.display();
          return;
        }
        try {
          this.plugin.data.tokens = await authenticate({
            clientId: this.plugin.data.settings.clientId.trim(),
            clientSecret: this.plugin.data.settings.clientSecret.trim()
          });
          await this.plugin.savePluginData();
          const email = await this.plugin.getClient().getAccountEmail();
          new import_obsidian4.Notice(`Connected to Google Drive as ${email}`);
          this.display();
        } catch (e) {
          new import_obsidian4.Notice(`Google sign-in failed: ${e instanceof Error ? e.message : e}`, 1e4);
        }
      })
    );
    new import_obsidian4.Setting(containerEl).setName("OAuth client ID").setDesc("From Google Cloud Console \u2192 APIs & Services \u2192 Credentials.").addText(
      (t) => t.setPlaceholder("xxxx.apps.googleusercontent.com").setValue(this.plugin.data.settings.clientId).onChange(async (v) => {
        this.plugin.data.settings.clientId = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("OAuth client secret").setDesc("The client secret of your Desktop-app OAuth client. Stored locally in this vault's plugin data.").addText((t) => {
      t.inputEl.type = "password";
      t.setValue(this.plugin.data.settings.clientSecret).onChange(async (v) => {
        this.plugin.data.settings.clientSecret = v;
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Move auth to another device").setDesc(
      "Mobile can't run the Google sign-in flow. Connect on desktop, copy the auth bundle there, and paste it on your phone or tablet."
    ).addButton(
      (btn) => btn.setButtonText("Copy auth bundle").onClick(async () => {
        if (!this.plugin.data.tokens) {
          new import_obsidian4.Notice("Connect on this device first.");
          return;
        }
        const bundle = btoa(
          JSON.stringify({
            tokens: this.plugin.data.tokens,
            clientId: this.plugin.data.settings.clientId,
            clientSecret: this.plugin.data.settings.clientSecret
          })
        );
        await navigator.clipboard.writeText(bundle);
        new import_obsidian4.Notice("Auth bundle copied. Paste it on your other device. Treat it like a password.");
      })
    ).addButton(
      (btn) => btn.setButtonText("Paste auth bundle").onClick(async () => {
        var _a, _b, _c;
        try {
          const raw = await navigator.clipboard.readText();
          const parsed = JSON.parse(atob(raw.trim()));
          if (!((_a = parsed == null ? void 0 : parsed.tokens) == null ? void 0 : _a.refreshToken)) throw new Error("Not a valid auth bundle");
          this.plugin.data.tokens = parsed.tokens;
          this.plugin.data.settings.clientId = (_b = parsed.clientId) != null ? _b : this.plugin.data.settings.clientId;
          this.plugin.data.settings.clientSecret = (_c = parsed.clientSecret) != null ? _c : this.plugin.data.settings.clientSecret;
          await this.plugin.savePluginData();
          new import_obsidian4.Notice("Auth imported. This device can now sync.");
          this.display();
        } catch (e) {
          new import_obsidian4.Notice(`Import failed: ${e instanceof Error ? e.message : e}`);
        }
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Sync").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Drive folder name").setDesc("Folder created at the root of My Drive that holds this vault. Change before the first sync.").addText(
      (t) => t.setValue(this.plugin.data.settings.driveFolderName).onChange(async (v) => {
        this.plugin.data.settings.driveFolderName = v || "Obsidian Vault";
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Auto-sync interval (minutes)").setDesc("0 disables automatic sync; you can always run \u201CSync now\u201D from the command palette or ribbon.").addText(
      (t) => t.setValue(String(this.plugin.data.settings.autoSyncMinutes)).onChange(async (v) => {
        const n = Math.max(0, parseInt(v, 10) || 0);
        this.plugin.data.settings.autoSyncMinutes = n;
        await this.plugin.savePluginData();
        this.plugin.restartAutoSync();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Sync when Obsidian starts").setDesc("Pull the latest changes from Drive as soon as the app launches.").addToggle(
      (t) => t.setValue(this.plugin.data.settings.syncOnStart).onChange(async (v) => {
        this.plugin.data.settings.syncOnStart = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Sync shortly after edits").setDesc(
      "Automatically sync once you've stopped editing for the quiet period below \u2014 and immediately when you switch away from Obsidian or background the app. Long editing sessions can't postpone it indefinitely, and failed syncs are retried."
    ).addToggle(
      (t) => t.setValue(this.plugin.data.settings.syncOnChange).onChange(async (v) => {
        this.plugin.data.settings.syncOnChange = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Quiet period after edits (seconds)").setDesc("How long to wait after your last change before syncing. Minimum 5.").addText(
      (t) => t.setValue(String(this.plugin.data.settings.syncOnChangeDelaySeconds)).onChange(async (v) => {
        const n = Math.max(5, parseInt(v, 10) || 30);
        this.plugin.data.settings.syncOnChangeDelaySeconds = n;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("When a file changed in both places").setDesc(
      "\u201CAuto-merge\u201D combines both sets of edits line-by-line (like git) for text files, falling back to a conflict copy only when the same lines were edited on both sides."
    ).addDropdown(
      (d) => d.addOptions({
        "smart-merge": "Auto-merge, conflict copy if edits overlap (recommended)",
        "conflict-copy": "Keep both (conflict copy)",
        newest: "Keep the newest",
        "prefer-local": "Always keep this device's version",
        "prefer-remote": "Always keep the Drive version"
      }).setValue(this.plugin.data.settings.conflictStrategy).onChange(async (v) => {
        this.plugin.data.settings.conflictStrategy = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Deletion safety threshold").setDesc(
      "Ask for confirmation before a single sync deletes this many files or more. Protects against an accidentally emptied vault wiping your Drive copy. 0 disables."
    ).addText(
      (t) => t.setValue(String(this.plugin.data.settings.deletionGuardThreshold)).onChange(async (v) => {
        this.plugin.data.settings.deletionGuardThreshold = Math.max(0, parseInt(v, 10) || 0);
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Sync when window regains focus").setDesc("Pick up changes from other devices when you come back to Obsidian (at most once a minute).").addToggle(
      (t) => t.setValue(this.plugin.data.settings.syncOnFocus).onChange(async (v) => {
        this.plugin.data.settings.syncOnFocus = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Sync the .obsidian config folder").setDesc(
      "Sync themes, snippets, plugins, and settings across devices. Per-device files (workspace layout) are excluded below. This plugin's own data.json is never synced \u2014 it holds your Google tokens."
    ).addToggle(
      (t) => t.setValue(this.plugin.data.settings.syncConfigFolder).onChange(async (v) => {
        this.plugin.data.settings.syncConfigFolder = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Config paths to exclude").setDesc("One path per line, relative to .obsidian. Only used when config sync is on.").addTextArea(
      (t) => t.setValue(this.plugin.data.settings.configExcludes).onChange(async (v) => {
        this.plugin.data.settings.configExcludes = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Ignored paths").setDesc("One folder or file path per line (vault-relative). These are never uploaded or downloaded.").addTextArea(
      (t) => t.setPlaceholder("Private/\nScratch.md").setValue(this.plugin.data.settings.ignorePatterns).onChange(async (v) => {
        this.plugin.data.settings.ignorePatterns = v;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Encryption").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Encryption password").setDesc(
      "Non-empty enables end-to-end encryption: file content is AES-256-GCM encrypted before upload, so Google cannot read your notes (your Drive copy is no longer human-readable). Use the SAME password on every device. After enabling, run \u201CForce re-upload of all files\u201D to encrypt files already on Drive. If you lose the password, encrypted files on Drive are unrecoverable."
    ).addText((t) => {
      t.inputEl.type = "password";
      t.setValue(this.plugin.data.settings.encryptionPassword).onChange(async (v) => {
        this.plugin.data.settings.encryptionPassword = v;
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Show sync notices").setDesc("Pop up a summary after each sync. Errors are always shown.").addToggle(
      (t) => t.setValue(this.plugin.data.settings.verboseNotices).onChange(async (v) => {
        this.plugin.data.settings.verboseNotices = v;
        await this.plugin.savePluginData();
      })
    );
  }
};

// src/merge.ts
function diffHunks(base, side) {
  let prefix = 0;
  while (prefix < base.length && prefix < side.length && base[prefix] === side[prefix]) prefix++;
  let suffix = 0;
  while (suffix < base.length - prefix && suffix < side.length - prefix && base[base.length - 1 - suffix] === side[side.length - 1 - suffix])
    suffix++;
  const b = base.slice(prefix, base.length - suffix);
  const s = side.slice(prefix, side.length - suffix);
  const n = b.length;
  const m = s.length;
  if (n * m > 9e6) return null;
  if (n === 0 && m === 0) return [];
  if (n === 0 || m === 0) {
    return [{ baseStart: prefix, baseLen: n, sideStart: prefix, sideLen: m }];
  }
  const width = m + 1;
  const dp = new Uint32Array((n + 1) * width);
  for (let i2 = n - 1; i2 >= 0; i2--) {
    for (let j2 = m - 1; j2 >= 0; j2--) {
      dp[i2 * width + j2] = b[i2] === s[j2] ? dp[(i2 + 1) * width + j2 + 1] + 1 : Math.max(dp[(i2 + 1) * width + j2], dp[i2 * width + j2 + 1]);
    }
  }
  const hunks = [];
  let i = 0;
  let j = 0;
  let hunkI = -1;
  let hunkJ = -1;
  const flush = (endI, endJ) => {
    if (hunkI >= 0) {
      hunks.push({
        baseStart: hunkI + prefix,
        baseLen: endI - hunkI,
        sideStart: hunkJ + prefix,
        sideLen: endJ - hunkJ
      });
      hunkI = hunkJ = -1;
    }
  };
  while (i < n && j < m) {
    if (b[i] === s[j]) {
      flush(i, j);
      i++;
      j++;
    } else {
      if (hunkI < 0) {
        hunkI = i;
        hunkJ = j;
      }
      if (dp[(i + 1) * width + j] >= dp[i * width + j + 1]) i++;
      else j++;
    }
  }
  if (i < n || j < m) {
    if (hunkI < 0) {
      hunkI = i;
      hunkJ = j;
    }
  }
  flush(n, m);
  return hunks;
}
function mergeThreeWay(baseText, localText, remoteText) {
  const base = baseText.split("\n");
  const local = localText.split("\n");
  const remote = remoteText.split("\n");
  const localHunks = diffHunks(base, local);
  const remoteHunks = diffHunks(base, remote);
  if (!localHunks || !remoteHunks) return null;
  const hunks = [
    ...localHunks.map((h) => ({ ...h, side: 0 })),
    ...remoteHunks.map((h) => ({ ...h, side: 1 }))
  ].sort((a, b) => a.baseStart - b.baseStart || a.baseLen - b.baseLen);
  const out = [];
  let basePos = 0;
  let k = 0;
  while (k < hunks.length) {
    const gStart = hunks[k].baseStart;
    let gEnd = gStart + hunks[k].baseLen;
    let k2 = k + 1;
    while (k2 < hunks.length && (hunks[k2].baseStart < gEnd || hunks[k2].baseStart === gStart && gEnd === gStart)) {
      gEnd = Math.max(gEnd, hunks[k2].baseStart + hunks[k2].baseLen);
      k2++;
    }
    const group = hunks.slice(k, k2);
    for (let x = basePos; x < gStart; x++) out.push(base[x]);
    const sideSegment = (side) => {
      const sideLines = side === 0 ? local : remote;
      const own = group.filter((h) => h.side === side).sort((a, b) => a.baseStart - b.baseStart);
      const seg = [];
      let pos = gStart;
      for (const h of own) {
        for (let x = pos; x < h.baseStart; x++) seg.push(base[x]);
        for (let x = h.sideStart; x < h.sideStart + h.sideLen; x++) seg.push(sideLines[x]);
        pos = h.baseStart + h.baseLen;
      }
      for (let x = pos; x < gEnd; x++) seg.push(base[x]);
      return seg;
    };
    const key = (lines) => lines.join("\0");
    const localSeg = sideSegment(0);
    const remoteSeg = sideSegment(1);
    const baseSeg = base.slice(gStart, gEnd);
    let chosen;
    if (key(localSeg) === key(remoteSeg)) chosen = localSeg;
    else if (key(baseSeg) === key(localSeg)) chosen = remoteSeg;
    else if (key(baseSeg) === key(remoteSeg)) chosen = localSeg;
    else return null;
    for (const line of chosen) out.push(line);
    basePos = gEnd;
    k = k2;
  }
  for (let x = basePos; x < base.length; x++) out.push(base[x]);
  return out.join("\n");
}
var TEXT_EXTENSIONS = /* @__PURE__ */ new Set([
  "md",
  "markdown",
  "txt",
  "text",
  "org",
  "tex",
  "canvas",
  "json",
  "csv",
  "tsv",
  "yml",
  "yaml",
  "xml",
  "html",
  "htm",
  "css",
  "js",
  "ts",
  "ini",
  "cfg",
  "log"
]);
function isMergeableTextPath(path) {
  const dot = path.lastIndexOf(".");
  if (dot < 0 || dot < path.lastIndexOf("/")) return false;
  return TEXT_EXTENSIONS.has(path.slice(dot + 1).toLowerCase());
}

// src/planner.ts
async function planSync(input) {
  const { local, remote, state } = input;
  let actions = [];
  let unchanged = 0;
  const allPaths = /* @__PURE__ */ new Set([...local.keys(), ...remote.keys(), ...Object.keys(state)]);
  for (const path of allPaths) {
    const l = local.get(path);
    const r = remote.get(path);
    const s = state[path];
    if (l && r) {
      if (!s) {
        actions.push({ type: "inspect", path, remote: r });
        continue;
      }
      const localChanged = await input.isLocalChanged(path);
      const remoteChanged = r.md5 !== s.remoteMd5;
      if (localChanged && remoteChanged) actions.push({ type: "conflict", path, remote: r });
      else if (localChanged) actions.push({ type: "upload-update", path, remoteId: r.id });
      else if (remoteChanged) actions.push({ type: "download", path, remote: r });
      else if (s.remoteId !== r.id) actions.push({ type: "refresh-id", path, remoteId: r.id });
      else unchanged++;
    } else if (l && !r) {
      if (!s) actions.push({ type: "upload-new", path });
      else if (await input.isLocalChanged(path)) actions.push({ type: "upload-new", path });
      else actions.push({ type: "delete-local", path });
    } else if (!l && r) {
      if (!s) actions.push({ type: "download", path, remote: r });
      else if (r.md5 !== s.remoteMd5) actions.push({ type: "download", path, remote: r });
      else actions.push({ type: "delete-remote", path, remoteId: s.remoteId });
    } else if (s) {
      actions.push({ type: "forget", path });
    }
  }
  actions = await detectRenames(actions, input);
  const deletionPaths = actions.filter((a) => a.type === "delete-local" || a.type === "delete-remote").map((a) => a.path);
  return { actions, deletionPaths, unchanged };
}
async function detectRenames(actions, input) {
  const consumed = /* @__PURE__ */ new Set();
  const renames = [];
  const remoteDeletes = actions.filter(
    (a) => a.type === "delete-remote"
  );
  if (remoteDeletes.length) {
    for (const a of actions) {
      if (a.type !== "upload-new" || input.state[a.path]) continue;
      const hash = await input.localHash(a.path);
      const match = remoteDeletes.find((d) => {
        var _a;
        return !consumed.has(d) && ((_a = input.state[d.path]) == null ? void 0 : _a.localHash) === hash;
      });
      if (match) {
        consumed.add(a);
        consumed.add(match);
        renames.push({ type: "rename-remote", from: match.path, to: a.path, remoteId: match.remoteId });
      }
    }
  }
  const localDeletes = actions.filter(
    (a) => a.type === "delete-local"
  );
  if (localDeletes.length) {
    for (const a of actions) {
      if (a.type !== "download" || input.state[a.path]) continue;
      const match = localDeletes.find(
        (d) => {
          var _a, _b;
          return !consumed.has(d) && ((_a = input.state[d.path]) == null ? void 0 : _a.remoteId) === a.remote.id && ((_b = input.state[d.path]) == null ? void 0 : _b.remoteMd5) === a.remote.md5;
        }
      );
      if (match) {
        consumed.add(a);
        consumed.add(match);
        renames.push({ type: "rename-local", from: match.path, to: a.path, remote: a.remote });
      }
    }
  }
  if (!consumed.size) return actions;
  return actions.filter((a) => !consumed.has(a)).concat(renames);
}
function dirname(path) {
  const i = path.lastIndexOf("/");
  return i < 0 ? "" : path.slice(0, i);
}
function basename(path) {
  return path.slice(path.lastIndexOf("/") + 1);
}

// src/sync.ts
var MARKER_NAME = ".obsidian-drive-meta.json";
var TRANSFER_CONCURRENCY = 4;
var VaultMismatchError = class extends Error {
  constructor() {
    super(
      "The Drive folder belongs to a different vault. Change the Drive folder name in settings, or run \u201CAdopt Drive folder\u201D to link this vault to it."
    );
  }
};
async function sha256Hex(data) {
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
function randomId() {
  const bytes = new Uint8Array(12);
  crypto.getRandomValues(bytes);
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("");
}
function conflictCopyPath(path) {
  const stamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 16).replace("T", " ").replace(":", "");
  const dot = path.lastIndexOf(".");
  const slash = path.lastIndexOf("/");
  if (dot > slash) return `${path.slice(0, dot)} (conflict ${stamp})${path.slice(dot)}`;
  return `${path} (conflict ${stamp})`;
}
function isIgnored(path, prefixes) {
  return prefixes.some((p) => path === p || path.startsWith(p.endsWith("/") ? p : p + "/"));
}
async function runPool(items, limit, fn) {
  let next = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (; ; ) {
      const index = next++;
      if (index >= items.length) return;
      await fn(items[index]);
    }
  });
  await Promise.all(workers);
}
async function checkMarker(ctx, baseFolderId, wantSalt) {
  var _a;
  const { client, data } = ctx;
  const existing = await client.findByName(MARKER_NAME, baseFolderId);
  if (existing) {
    const marker2 = JSON.parse(new TextDecoder().decode(await client.download(existing.id)));
    if (!data.vaultId) data.vaultId = marker2.vaultId;
    else if (data.vaultId !== marker2.vaultId) throw new VaultMismatchError();
    if (wantSalt && !marker2.salt) {
      marker2.salt = generateSaltB64();
      const body2 = new TextEncoder().encode(JSON.stringify(marker2)).buffer;
      await client.uploadUpdate(existing.id, body2);
    }
    return marker2;
  }
  const marker = { vaultId: (_a = data.vaultId) != null ? _a : randomId() };
  if (wantSalt) marker.salt = generateSaltB64();
  data.vaultId = marker.vaultId;
  const body = new TextEncoder().encode(JSON.stringify(marker)).buffer;
  await client.uploadNew(MARKER_NAME, baseFolderId, body);
  return marker;
}
async function adoptDriveFolder(ctx, folderName) {
  const baseFolderId = await ctx.client.ensureBaseFolder(folderName, ctx.data.baseFolderId);
  ctx.data.baseFolderId = baseFolderId;
  const existing = await ctx.client.findByName(MARKER_NAME, baseFolderId);
  if (existing) {
    const marker = JSON.parse(new TextDecoder().decode(await ctx.client.download(existing.id)));
    ctx.data.vaultId = marker.vaultId;
  } else {
    ctx.data.vaultId = null;
  }
  ctx.data.state = {};
  ctx.data.changesPageToken = null;
  await ctx.saveData();
}
function anyRelevantChanges(changes, data, baseFolderId) {
  var _a, _b;
  const idToPath = /* @__PURE__ */ new Map();
  for (const [path, s] of Object.entries(data.state)) idToPath.set(s.remoteId, path);
  const folderIdToPath = /* @__PURE__ */ new Map();
  folderIdToPath.set(baseFolderId, "");
  for (const [path, id] of Object.entries(data.folderIds)) folderIdToPath.set(id, path);
  for (const ch of changes) {
    const knownFile = idToPath.get(ch.fileId);
    const knownFolder = folderIdToPath.get(ch.fileId);
    if (ch.removed || ((_a = ch.file) == null ? void 0 : _a.trashed)) {
      if (knownFile !== void 0 || knownFolder !== void 0 && knownFolder !== "") return true;
      continue;
    }
    const f = ch.file;
    if (!f || f.name === MARKER_NAME) continue;
    if (knownFile !== void 0) {
      const s = data.state[knownFile];
      if (f.md5Checksum !== void 0 && f.md5Checksum !== s.remoteMd5) return true;
      if (f.name !== basename(knownFile)) return true;
      const parentPath = dirname(knownFile);
      const expectedParent = parentPath === "" ? baseFolderId : data.folderIds[parentPath];
      if (expectedParent && f.parents && !f.parents.includes(expectedParent)) return true;
      continue;
    }
    if (knownFolder !== void 0) {
      if (knownFolder === "") continue;
      if (f.name !== basename(knownFolder)) return true;
      const parentPath = dirname(knownFolder);
      const expectedParent = parentPath === "" ? baseFolderId : data.folderIds[parentPath];
      if (expectedParent && f.parents && !f.parents.includes(expectedParent)) return true;
      continue;
    }
    if ((_b = f.parents) == null ? void 0 : _b.some((p) => folderIdToPath.has(p))) return true;
  }
  return false;
}
async function performSync(ctx, opts) {
  var _a, _b, _c, _d, _e;
  const { client, data, io } = ctx;
  (_a = ctx.onProgress) == null ? void 0 : _a.call(ctx, "Checking Drive folder\u2026");
  const baseFolderId = await client.ensureBaseFolder(opts.driveFolderName, data.baseFolderId);
  if (baseFolderId !== data.baseFolderId) {
    data.baseFolderId = baseFolderId;
    data.changesPageToken = null;
    await ctx.saveData();
  }
  const wantEncryption = opts.encryptionPassword.length > 0;
  const marker = await checkMarker(ctx, baseFolderId, wantEncryption);
  data.encryptionSalt = (_b = marker.salt) != null ? _b : null;
  await ctx.saveData();
  const codec = wantEncryption && marker.salt ? await createEncryptionCodec(opts.encryptionPassword, marker.salt) : plaintextCodec;
  let fastPath = false;
  let nextChangesToken = null;
  if (!opts.dryRun && data.changesPageToken) {
    try {
      const { changes, newStartPageToken } = await client.listChanges(data.changesPageToken);
      if (!anyRelevantChanges(changes, data, baseFolderId)) {
        fastPath = true;
        nextChangesToken = newStartPageToken;
        ctx.log(`Fast path: ${changes.length} remote change(s), none relevant`);
      }
    } catch (e) {
      ctx.log(`Changes cursor invalid, falling back to full listing: ${e instanceof Error ? e.message : e}`);
      data.changesPageToken = null;
    }
  }
  (_c = ctx.onProgress) == null ? void 0 : _c.call(ctx, "Scanning vault\u2026");
  const localAll = await io.listAll(opts.includeConfig, opts.configExcludes);
  const local = /* @__PURE__ */ new Map();
  for (const [path, meta] of localAll) {
    if (!isIgnored(path, opts.ignorePrefixes)) local.set(path, meta);
  }
  let remote;
  let folders;
  if (fastPath) {
    remote = /* @__PURE__ */ new Map();
    for (const [path, s] of Object.entries(data.state)) {
      remote.set(path, { id: s.remoteId, md5: s.remoteMd5, modifiedTime: 0 });
    }
    folders = new Map(Object.entries(data.folderIds));
    folders.set("", baseFolderId);
  } else {
    if (!opts.dryRun) nextChangesToken = await client.getStartPageToken();
    (_d = ctx.onProgress) == null ? void 0 : _d.call(ctx, "Listing Google Drive\u2026");
    const listing = await client.listTree(baseFolderId);
    listing.files.delete(MARKER_NAME);
    remote = /* @__PURE__ */ new Map();
    for (const [path, rf] of listing.files) {
      if (!isIgnored(path, opts.ignorePrefixes)) {
        remote.set(path, { id: rf.id, md5: rf.md5, modifiedTime: rf.modifiedTime });
      }
    }
    folders = listing.folders;
  }
  const hashCache = /* @__PURE__ */ new Map();
  const localHash = async (path) => {
    const cached = hashCache.get(path);
    if (cached) return cached;
    const hash = await sha256Hex(await io.read(path));
    hashCache.set(path, hash);
    return hash;
  };
  const isLocalChanged = async (path) => {
    const s = data.state[path];
    const m = local.get(path);
    if (!s || !m) return true;
    if (m.mtime === s.mtime && m.size === s.size) return false;
    return await localHash(path) !== s.localHash;
  };
  (_e = ctx.onProgress) == null ? void 0 : _e.call(ctx, "Planning\u2026");
  const plan = await planSync({ local, remote, state: data.state, isLocalChanged, localHash });
  if (opts.dryRun) return { plan, fastPath };
  const report = {
    uploaded: 0,
    downloaded: 0,
    deletedLocal: 0,
    deletedRemote: 0,
    renamed: 0,
    conflicts: 0,
    merged: 0,
    skipped: plan.unchanged,
    errors: [],
    aborted: false,
    fastPath
  };
  if (opts.deletionGuardThreshold > 0 && plan.deletionPaths.length >= opts.deletionGuardThreshold) {
    ctx.log(`Deletion guard: sync wants to delete ${plan.deletionPaths.length} files, asking for confirmation`);
    if (!await ctx.confirmDeletions(plan.deletionPaths)) {
      report.aborted = true;
      ctx.log("Sync aborted by deletion guard");
      return report;
    }
  }
  const newDirs = /* @__PURE__ */ new Set();
  for (const a of plan.actions) {
    if (a.type === "upload-new") newDirs.add(dirname(a.path));
    if (a.type === "rename-remote") newDirs.add(dirname(a.to));
  }
  for (const dir of newDirs) await client.ensureFolderPath(dir, folders);
  let saveChain = Promise.resolve();
  const queueSave = () => {
    saveChain = saveChain.then(() => ctx.saveData()).catch(() => void 0);
  };
  let done = 0;
  const executor = new ActionExecutor(ctx, codec, folders, local, opts.conflictStrategy, report, localHash);
  await runPool(plan.actions, TRANSFER_CONCURRENCY, async (action) => {
    var _a2;
    try {
      await executor.execute(action);
    } catch (e) {
      const path = "path" in action ? action.path : action.to;
      report.errors.push(`${path}: ${e instanceof Error ? e.message : String(e)}`);
      ctx.log(`ERROR ${path}: ${e instanceof Error ? e.message : e}`);
    }
    done++;
    if (done % 20 === 0) {
      (_a2 = ctx.onProgress) == null ? void 0 : _a2.call(ctx, `Syncing\u2026 ${done}/${plan.actions.length}`);
      queueSave();
    }
  });
  if (nextChangesToken) data.changesPageToken = nextChangesToken;
  data.folderIds = Object.fromEntries([...folders].filter(([path]) => path !== ""));
  await saveChain;
  await ctx.saveData();
  return report;
}
var ActionExecutor = class {
  constructor(ctx, codec, folders, local, strategy, report, localHash) {
    this.ctx = ctx;
    this.codec = codec;
    this.folders = folders;
    this.local = local;
    this.strategy = strategy;
    this.report = report;
    this.localHash = localHash;
  }
  async execute(action) {
    var _a, _b, _c, _d;
    const { ctx, report } = this;
    const state = ctx.data.state;
    switch (action.type) {
      case "upload-new":
      case "upload-update": {
        await this.upload(action.path, action.type === "upload-update" ? action.remoteId : void 0);
        break;
      }
      case "download": {
        await this.download(action.path, action.remote);
        break;
      }
      case "delete-local": {
        await ctx.io.remove(action.path);
        delete state[action.path];
        report.deletedLocal++;
        ctx.log(`Deleted locally: ${action.path}`);
        break;
      }
      case "delete-remote": {
        await ctx.client.trash(action.remoteId);
        delete state[action.path];
        report.deletedRemote++;
        ctx.log(`Trashed on Drive: ${action.path}`);
        break;
      }
      case "rename-remote": {
        const parents = await ctx.client.getParents(action.remoteId);
        const newParent = this.folders.get(dirname(action.to));
        if (!newParent) throw new Error(`Missing Drive folder for ${action.to}`);
        await ctx.client.move(action.remoteId, basename(action.to), newParent, parents);
        const s = state[action.from];
        const meta = this.local.get(action.to);
        state[action.to] = {
          remoteId: action.remoteId,
          localHash: s.localHash,
          remoteMd5: s.remoteMd5,
          mtime: (_a = meta == null ? void 0 : meta.mtime) != null ? _a : 0,
          size: (_b = meta == null ? void 0 : meta.size) != null ? _b : s.size
        };
        delete state[action.from];
        report.renamed++;
        ctx.log(`Renamed on Drive: ${action.from} \u2192 ${action.to}`);
        break;
      }
      case "rename-local": {
        const s = state[action.from];
        const meta = await ctx.io.rename(action.from, action.to);
        state[action.to] = {
          remoteId: action.remote.id,
          localHash: s.localHash,
          remoteMd5: action.remote.md5,
          mtime: meta.mtime,
          size: meta.size
        };
        delete state[action.from];
        report.renamed++;
        ctx.log(`Renamed locally: ${action.from} \u2192 ${action.to}`);
        break;
      }
      case "refresh-id": {
        state[action.path].remoteId = action.remoteId;
        report.skipped++;
        break;
      }
      case "forget": {
        delete state[action.path];
        break;
      }
      case "inspect": {
        const localData = await ctx.io.read(action.path);
        const localHashValue = await sha256Hex(localData);
        const remoteData = await this.codec.decode(await ctx.client.download(action.remote.id));
        if (await sha256Hex(remoteData) === localHashValue) {
          const meta = this.local.get(action.path);
          state[action.path] = {
            remoteId: action.remote.id,
            localHash: localHashValue,
            remoteMd5: action.remote.md5,
            mtime: (_c = meta == null ? void 0 : meta.mtime) != null ? _c : 0,
            size: (_d = meta == null ? void 0 : meta.size) != null ? _d : localData.byteLength
          };
          this.report.skipped++;
        } else {
          await this.resolveConflict(action.path, action.remote, void 0);
        }
        break;
      }
      case "conflict": {
        await this.resolveConflict(action.path, action.remote, state[action.path]);
        break;
      }
    }
  }
  async upload(path, existingId) {
    var _a, _b;
    const { ctx } = this;
    const raw = await ctx.io.read(path);
    const hash = await sha256Hex(raw);
    const encoded = await this.codec.encode(raw);
    let remoteId;
    let md5;
    if (existingId) {
      remoteId = existingId;
      md5 = (await ctx.client.uploadUpdate(existingId, encoded)).md5;
    } else {
      const parentId = this.folders.get(dirname(path));
      if (!parentId) throw new Error(`Missing Drive folder for ${path}`);
      const created = await ctx.client.uploadNew(basename(path), parentId, encoded);
      remoteId = created.id;
      md5 = created.md5;
    }
    const meta = this.local.get(path);
    ctx.data.state[path] = {
      remoteId,
      localHash: hash,
      remoteMd5: md5,
      mtime: (_a = meta == null ? void 0 : meta.mtime) != null ? _a : 0,
      size: (_b = meta == null ? void 0 : meta.size) != null ? _b : raw.byteLength
    };
    this.report.uploaded++;
    ctx.log(`Uploaded: ${path}`);
  }
  async download(path, remote) {
    const { ctx } = this;
    const data = await this.codec.decode(await ctx.client.download(remote.id));
    const meta = await ctx.io.write(path, data);
    ctx.data.state[path] = {
      remoteId: remote.id,
      localHash: await sha256Hex(data),
      remoteMd5: remote.md5,
      mtime: meta.mtime,
      size: meta.size
    };
    this.report.downloaded++;
    ctx.log(`Downloaded: ${path}`);
  }
  async resolveConflict(path, remote, known) {
    var _a;
    const { ctx } = this;
    this.report.conflicts++;
    switch (this.strategy) {
      case "smart-merge": {
        if (known && await this.trySmartMerge(path, remote, known)) return;
        await this.saveConflictCopy(path, remote);
        return;
      }
      case "conflict-copy":
        await this.saveConflictCopy(path, remote);
        return;
      case "prefer-local":
        await this.upload(path, remote.id);
        return;
      case "prefer-remote":
        await this.download(path, remote);
        return;
      case "newest": {
        const meta = this.local.get(path);
        if (((_a = meta == null ? void 0 : meta.mtime) != null ? _a : 0) >= remote.modifiedTime) await this.upload(path, remote.id);
        else await this.download(path, remote);
        return;
      }
    }
  }
  async saveConflictCopy(path, remote) {
    const { ctx } = this;
    const remoteData = await this.codec.decode(await ctx.client.download(remote.id));
    const copyPath = conflictCopyPath(path);
    await ctx.io.write(copyPath, remoteData);
    ctx.log(`Conflict on ${path} \u2014 remote version saved as ${copyPath}`);
    await this.upload(path, remote.id);
  }
  async trySmartMerge(path, remote, known) {
    const { ctx } = this;
    if (!isMergeableTextPath(path)) return false;
    const revisionId = await ctx.client.findRevisionByMd5(remote.id, known.remoteMd5);
    if (!revisionId) return false;
    const decoder = new TextDecoder();
    const baseText = decoder.decode(await this.codec.decode(await ctx.client.downloadRevision(remote.id, revisionId)));
    const localText = decoder.decode(await ctx.io.read(path));
    const remoteText = decoder.decode(await this.codec.decode(await ctx.client.download(remote.id)));
    const mergedText = mergeThreeWay(baseText, localText, remoteText);
    if (mergedText === null) return false;
    const mergedData = new TextEncoder().encode(mergedText).buffer;
    const meta = await ctx.io.write(path, mergedData);
    const uploaded = await ctx.client.uploadUpdate(remote.id, await this.codec.encode(mergedData));
    ctx.data.state[path] = {
      remoteId: remote.id,
      localHash: await sha256Hex(mergedData),
      remoteMd5: uploaded.md5,
      mtime: meta.mtime,
      size: meta.size
    };
    this.report.merged++;
    ctx.log(`Auto-merged both edits of ${path}`);
    return true;
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  clientId: "",
  clientSecret: "",
  driveFolderName: "Obsidian Vault",
  autoSyncMinutes: 15,
  syncOnStart: true,
  syncOnChange: true,
  syncOnChangeDelaySeconds: 30,
  conflictStrategy: "smart-merge",
  ignorePatterns: "",
  verboseNotices: true,
  deletionGuardThreshold: 10,
  syncConfigFolder: false,
  configExcludes: "workspace.json\nworkspace-mobile.json",
  encryptionPassword: "",
  syncOnFocus: true
};

// src/vaultio.ts
var import_obsidian5 = require("obsidian");
var _VaultIO = class _VaultIO {
  constructor(app) {
    this.app = app;
  }
  get configDir() {
    return this.app.vault.configDir;
  }
  isConfigPath(path) {
    return path === this.configDir || path.startsWith(this.configDir + "/");
  }
  async listAll(includeConfig, configExcludes) {
    const out = /* @__PURE__ */ new Map();
    for (const file of this.app.vault.getFiles()) {
      out.set(file.path, { path: file.path, mtime: file.stat.mtime, size: file.stat.size });
    }
    if (includeConfig) {
      const excludes = [...configExcludes, _VaultIO.SELF_EXCLUDE].map((e) => e.trim().replace(/^\/+|\/+$/g, "")).filter((e) => e.length > 0).map((e) => `${this.configDir}/${e}`);
      const isExcluded = (p) => excludes.some((e) => p === e || p.startsWith(e + "/"));
      const adapter = this.app.vault.adapter;
      const queue = [this.configDir];
      while (queue.length) {
        const dir = queue.shift();
        let listing;
        try {
          listing = await adapter.list(dir);
        } catch (e) {
          continue;
        }
        for (const sub of listing.folders) {
          if (!isExcluded(sub)) queue.push(sub);
        }
        for (const filePath of listing.files) {
          if (isExcluded(filePath)) continue;
          const stat = await adapter.stat(filePath);
          if ((stat == null ? void 0 : stat.type) === "file") {
            out.set(filePath, { path: filePath, mtime: stat.mtime, size: stat.size });
          }
        }
      }
    }
    return out;
  }
  async read(path) {
    if (this.isConfigPath(path)) {
      return this.app.vault.adapter.readBinary((0, import_obsidian5.normalizePath)(path));
    }
    const file = this.app.vault.getFileByPath((0, import_obsidian5.normalizePath)(path));
    if (!file) throw new Error(`Local file not found: ${path}`);
    return this.app.vault.readBinary(file);
  }
  async mkdirp(dir) {
    if (!dir) return;
    const parts = dir.split("/");
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const p = (0, import_obsidian5.normalizePath)(current);
      if (this.isConfigPath(p)) {
        if (!await this.app.vault.adapter.exists(p)) await this.app.vault.adapter.mkdir(p);
      } else if (!this.app.vault.getFolderByPath(p)) {
        await this.app.vault.createFolder(p);
      }
    }
  }
  async write(path, data) {
    var _a, _b;
    const dir = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "";
    await this.mkdirp(dir);
    const p = (0, import_obsidian5.normalizePath)(path);
    if (this.isConfigPath(p)) {
      await this.app.vault.adapter.writeBinary(p, data);
      const stat = await this.app.vault.adapter.stat(p);
      return { path, mtime: (_a = stat == null ? void 0 : stat.mtime) != null ? _a : Date.now(), size: (_b = stat == null ? void 0 : stat.size) != null ? _b : data.byteLength };
    }
    const existing = this.app.vault.getFileByPath(p);
    const file = existing ? (await this.app.vault.modifyBinary(existing, data), existing) : await this.app.vault.createBinary(p, data);
    return { path, mtime: file.stat.mtime, size: file.stat.size };
  }
  async remove(path) {
    const p = (0, import_obsidian5.normalizePath)(path);
    if (this.isConfigPath(p)) {
      await this.app.vault.adapter.remove(p);
      return;
    }
    const file = this.app.vault.getFileByPath(p);
    if (file) await this.app.vault.trash(file, false);
  }
  async rename(from, to) {
    var _a, _b;
    const toDir = to.includes("/") ? to.slice(0, to.lastIndexOf("/")) : "";
    await this.mkdirp(toDir);
    const fromP = (0, import_obsidian5.normalizePath)(from);
    const toP = (0, import_obsidian5.normalizePath)(to);
    if (this.isConfigPath(fromP)) {
      await this.app.vault.adapter.rename(fromP, toP);
      const stat = await this.app.vault.adapter.stat(toP);
      return { path: to, mtime: (_a = stat == null ? void 0 : stat.mtime) != null ? _a : Date.now(), size: (_b = stat == null ? void 0 : stat.size) != null ? _b : 0 };
    }
    const file = this.app.vault.getFileByPath(fromP);
    if (!file) throw new Error(`Local file not found: ${from}`);
    await this.app.vault.rename(file, toP);
    return { path: to, mtime: file.stat.mtime, size: file.stat.size };
  }
};
/**
 * The plugin's own data file — never synced (holds OAuth tokens and
 * per-device sync state). The plugin's code files DO sync, so updating
 * the plugin on one device propagates it to the others.
 */
_VaultIO.SELF_EXCLUDE = "plugins/google-drive-sync/data.json";
var VaultIO = _VaultIO;

// src/main.ts
var DriveSyncPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.data = this.emptyData();
    this.log = new SyncLog();
    this.client = null;
    this.io = null;
    this.syncing = false;
    this.lastSyncEnd = 0;
    this.autoSyncTimer = null;
    this.changeTimer = null;
    /** Set on every vault event; cleared when a sync starts. Edits made while a
     *  sync is running set it again so a follow-up sync picks them up. */
    this.pendingChanges = false;
    /** When the oldest not-yet-synced edit happened; bounds the debounce. */
    this.firstPendingChangeAt = null;
    this.autoSyncFailures = 0;
    this.statusBar = null;
  }
  emptyData() {
    return {
      settings: { ...DEFAULT_SETTINGS },
      tokens: null,
      state: {},
      baseFolderId: null,
      vaultId: null,
      encryptionSalt: null,
      changesPageToken: null,
      folderIds: {}
    };
  }
  async onload() {
    await this.loadPluginData();
    this.io = new VaultIO(this.app);
    this.addSettingTab(new DriveSyncSettingTab(this.app, this));
    this.statusBar = this.addStatusBarItem();
    this.setStatus("Drive: idle");
    this.addRibbonIcon("refresh-cw", "Sync with Google Drive", () => void this.syncNow());
    this.addCommand({ id: "sync-now", name: "Sync now", callback: () => void this.syncNow() });
    this.addCommand({
      id: "preview-sync",
      name: "Preview sync (dry run)",
      callback: () => void this.previewSync()
    });
    this.addCommand({
      id: "version-history",
      name: "View version history for current file",
      callback: () => void this.showVersionHistory()
    });
    this.addCommand({
      id: "view-sync-log",
      name: "View sync log",
      callback: () => new LogModal(this.app, this.log.text).open()
    });
    this.addCommand({
      id: "adopt-drive-folder",
      name: "Adopt Drive folder (link this vault to the existing Drive folder)",
      callback: () => void this.adoptFolder()
    });
    this.addCommand({
      id: "force-upload-all",
      name: "Force re-upload of all files (use after enabling encryption)",
      callback: () => void this.forceUploadAll()
    });
    this.addCommand({
      id: "reset-sync-state",
      name: "Reset sync state (next sync re-compares every file)",
      callback: async () => {
        this.data.state = {};
        this.data.baseFolderId = null;
        this.data.changesPageToken = null;
        this.data.folderIds = {};
        await this.savePluginData();
        new import_obsidian6.Notice("Sync state cleared. The next sync will re-compare all files against Drive.");
      }
    });
    this.restartAutoSync();
    this.app.workspace.onLayoutReady(() => {
      if (this.data.settings.syncOnStart) void this.syncNow(true);
      const onChange = () => this.scheduleChangeSync();
      this.registerEvent(this.app.vault.on("create", onChange));
      this.registerEvent(this.app.vault.on("modify", onChange));
      this.registerEvent(this.app.vault.on("delete", onChange));
      this.registerEvent(this.app.vault.on("rename", onChange));
      const syncOnResume = () => {
        if (!this.data.settings.syncOnFocus) return;
        if (Date.now() - this.lastSyncEnd > 6e4) void this.syncNow(true);
      };
      this.registerDomEvent(window, "focus", syncOnResume);
      this.registerDomEvent(window, "blur", () => this.flushPendingChanges());
      this.registerDomEvent(document, "visibilitychange", () => {
        if (document.hidden) this.flushPendingChanges();
        else syncOnResume();
      });
    });
  }
  onunload() {
    if (this.autoSyncTimer !== null) window.clearInterval(this.autoSyncTimer);
    if (this.changeTimer !== null) window.clearTimeout(this.changeTimer);
  }
  getClient() {
    if (!this.client) {
      this.client = new DriveClient(async (forceRefresh) => {
        if (!this.data.tokens) throw new Error("Not connected to Google Drive");
        if (forceRefresh) this.data.tokens.expiresAt = 0;
        const fresh = await ensureFreshTokens(
          {
            clientId: this.data.settings.clientId.trim(),
            clientSecret: this.data.settings.clientSecret.trim()
          },
          this.data.tokens
        );
        if (fresh !== this.data.tokens) {
          this.data.tokens = fresh;
          await this.savePluginData();
        }
        return fresh.accessToken;
      });
    }
    return this.client;
  }
  restartAutoSync() {
    if (this.autoSyncTimer !== null) {
      window.clearInterval(this.autoSyncTimer);
      this.autoSyncTimer = null;
    }
    const minutes = this.data.settings.autoSyncMinutes;
    if (minutes > 0) {
      this.autoSyncTimer = window.setInterval(() => void this.syncNow(true), minutes * 6e4);
      this.registerInterval(this.autoSyncTimer);
    }
  }
  quietPeriodMs() {
    return Math.max(5, this.data.settings.syncOnChangeDelaySeconds) * 1e3;
  }
  /** Debounced sync after edits: waits for a quiet period, then syncs. */
  scheduleChangeSync() {
    if (!this.data.settings.syncOnChange || !this.data.tokens) return;
    this.pendingChanges = true;
    if (this.syncing) return;
    const now = Date.now();
    if (this.firstPendingChangeAt === null) this.firstPendingChangeAt = now;
    const quiet = this.quietPeriodMs();
    const maxWait = Math.max(4 * quiet, 6e4);
    const delay = Math.min(quiet, Math.max(this.firstPendingChangeAt + maxWait - now, 1e3));
    if (this.changeTimer !== null) window.clearTimeout(this.changeTimer);
    this.changeTimer = window.setTimeout(() => {
      this.changeTimer = null;
      void this.syncNow(true);
    }, delay);
  }
  /** Sync unsynced edits right now, skipping the quiet period. Called when the
   *  app loses focus or is backgrounded: timers may never fire after that. */
  flushPendingChanges() {
    if (!this.pendingChanges || this.syncing) return;
    if (!this.data.settings.syncOnChange || !this.data.tokens) return;
    if (this.changeTimer !== null) {
      window.clearTimeout(this.changeTimer);
      this.changeTimer = null;
    }
    void this.syncNow(true);
  }
  /** After a sync: re-run for edits made while it was in flight, or retry a
   *  failure with backoff (offline, token hiccup) so edits aren't stranded
   *  until the next periodic sync. */
  scheduleFollowUpSync(afterFailure) {
    if (!this.data.settings.syncOnChange || !this.data.tokens) return;
    if (this.changeTimer !== null) return;
    const quiet = this.quietPeriodMs();
    const delay = afterFailure ? Math.min(quiet * 2 ** Math.min(this.autoSyncFailures, 6), 10 * 6e4) : quiet;
    this.changeTimer = window.setTimeout(() => {
      this.changeTimer = null;
      void this.syncNow(true);
    }, delay);
  }
  buildContext() {
    return {
      io: this.io,
      client: this.getClient(),
      data: this.data,
      saveData: () => this.savePluginData(),
      log: (m) => this.log.add(m),
      onProgress: (m) => this.setStatus(`Drive: ${m}`),
      confirmDeletions: (paths) => ConfirmModal.ask(
        this.app,
        "Confirm bulk deletion",
        [
          `This sync wants to delete ${paths.length} files (locally and/or on Drive).`,
          `Examples: ${paths.slice(0, 5).join(", ")}${paths.length > 5 ? ", \u2026" : ""}`,
          "If you recently emptied or moved things intentionally, proceed. If this is unexpected, cancel and check your vault."
        ],
        `Delete ${paths.length} files`
      )
    };
  }
  buildRunOptions(dryRun = false) {
    const s = this.data.settings;
    return {
      dryRun,
      conflictStrategy: s.conflictStrategy,
      ignorePrefixes: s.ignorePatterns.split("\n").map((l) => l.trim().replace(/^\/+|\/+$/g, "")).filter((l) => l.length > 0),
      includeConfig: s.syncConfigFolder,
      configExcludes: s.configExcludes.split("\n"),
      driveFolderName: s.driveFolderName.trim() || "Obsidian Vault",
      encryptionPassword: s.encryptionPassword,
      deletionGuardThreshold: s.deletionGuardThreshold
    };
  }
  async syncNow(background = false) {
    if (this.syncing) {
      if (!background) new import_obsidian6.Notice("Sync already in progress.");
      return;
    }
    if (!this.data.tokens) {
      if (!background) new import_obsidian6.Notice("Connect to Google Drive in the plugin settings first.");
      return;
    }
    this.syncing = true;
    if (this.changeTimer !== null) {
      window.clearTimeout(this.changeTimer);
      this.changeTimer = null;
    }
    this.pendingChanges = false;
    this.firstPendingChangeAt = null;
    this.setStatus("Drive: syncing\u2026");
    this.log.add(background ? "Sync started (automatic)" : "Sync started (manual)");
    let failed = false;
    try {
      const report = await performSync(this.buildContext(), this.buildRunOptions());
      this.reportResult(report, background);
      this.autoSyncFailures = 0;
    } catch (e) {
      failed = true;
      this.autoSyncFailures++;
      const msg = e instanceof Error ? e.message : String(e);
      if (!background || this.autoSyncFailures <= 1) new import_obsidian6.Notice(`Drive sync failed: ${msg}`, 1e4);
      this.log.add(`Sync failed: ${msg}`);
      console.error("[google-drive-sync]", e);
    } finally {
      this.syncing = false;
      this.lastSyncEnd = Date.now();
      this.setStatus(failed ? "Drive: sync failed" : `Drive: last sync ${(/* @__PURE__ */ new Date()).toLocaleTimeString()}`);
      if (failed) this.pendingChanges = true;
      if (this.pendingChanges) this.scheduleFollowUpSync(failed);
    }
  }
  async previewSync() {
    if (this.syncing) {
      new import_obsidian6.Notice("Sync in progress \u2014 try again when it finishes.");
      return;
    }
    if (!this.data.tokens) {
      new import_obsidian6.Notice("Connect to Google Drive in the plugin settings first.");
      return;
    }
    this.syncing = true;
    this.setStatus("Drive: previewing\u2026");
    try {
      const result = await performSync(this.buildContext(), this.buildRunOptions(true));
      new DryRunModal(this.app, result.plan).open();
    } catch (e) {
      new import_obsidian6.Notice(`Preview failed: ${e instanceof Error ? e.message : e}`, 1e4);
    } finally {
      this.syncing = false;
      this.setStatus("Drive: idle");
    }
  }
  async showVersionHistory() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian6.Notice("Open a file first.");
      return;
    }
    const known = this.data.state[file.path];
    if (!known || !this.data.tokens) {
      new import_obsidian6.Notice("This file hasn't been synced to Drive yet.");
      return;
    }
    try {
      const revisions = await this.getClient().listRevisionMeta(known.remoteId);
      new HistoryModal(this.app, file.path, revisions, async (revisionId) => {
        const ctx = this.buildContext();
        const raw = await ctx.client.downloadRevision(known.remoteId, revisionId);
        const password = this.data.settings.encryptionPassword;
        const salt = this.data.encryptionSalt;
        const codec = password && salt ? await createEncryptionCodec(password, salt) : plaintextCodec;
        await ctx.io.write(file.path, await codec.decode(raw));
      }).open();
    } catch (e) {
      new import_obsidian6.Notice(`Couldn't load version history: ${e instanceof Error ? e.message : e}`, 8e3);
    }
  }
  async adoptFolder() {
    const ok = await ConfirmModal.ask(
      this.app,
      "Adopt Drive folder",
      [
        `This links the current vault to the Drive folder \u201C${this.data.settings.driveFolderName}\u201D, even if it was created by a different vault.`,
        "Sync state is reset; the next sync merges the Drive folder's contents with this vault."
      ],
      "Adopt folder"
    );
    if (!ok) return;
    try {
      await adoptDriveFolder(this.buildContext(), this.data.settings.driveFolderName.trim() || "Obsidian Vault");
      new import_obsidian6.Notice("Drive folder adopted. Run \u201CSync now\u201D to merge.");
    } catch (e) {
      new import_obsidian6.Notice(`Adopt failed: ${e instanceof Error ? e.message : e}`, 8e3);
    }
  }
  async forceUploadAll() {
    const ok = await ConfirmModal.ask(
      this.app,
      "Force re-upload",
      [
        "Every synced file will be re-uploaded to Drive on the next sync, overwriting the remote copies.",
        "Use this after enabling encryption so existing remote files get encrypted too."
      ],
      "Re-upload everything"
    );
    if (!ok) return;
    for (const s of Object.values(this.data.state)) {
      s.localHash = "force-reupload";
      s.mtime = -1;
    }
    await this.savePluginData();
    void this.syncNow();
  }
  reportResult(report, background) {
    if (report.aborted) {
      new import_obsidian6.Notice("Drive sync cancelled \u2014 no files were deleted.", 8e3);
      return;
    }
    const changes = report.uploaded + report.downloaded + report.deletedLocal + report.deletedRemote + report.renamed + report.conflicts;
    if (report.errors.length) {
      new import_obsidian6.Notice(`Drive sync finished with ${report.errors.length} error(s). First: ${report.errors[0]}`, 1e4);
      console.error("[google-drive-sync] errors:", report.errors);
    }
    this.log.add(
      `Sync finished${report.fastPath ? " (fast path)" : ""}: ${report.uploaded} up, ${report.downloaded} down, ${report.renamed} renamed, ${report.deletedLocal + report.deletedRemote} deleted, ${report.merged} merged, ${report.errors.length} errors`
    );
    if (!this.data.settings.verboseNotices) return;
    if (background && changes === 0) return;
    const parts = [];
    if (report.uploaded) parts.push(`${report.uploaded} uploaded`);
    if (report.downloaded) parts.push(`${report.downloaded} downloaded`);
    if (report.renamed) parts.push(`${report.renamed} renamed`);
    if (report.deletedLocal) parts.push(`${report.deletedLocal} removed locally`);
    if (report.deletedRemote) parts.push(`${report.deletedRemote} removed on Drive`);
    if (report.merged) parts.push(`${report.merged} auto-merged`);
    const unresolved = report.conflicts - report.merged;
    if (unresolved > 0) parts.push(`${unresolved} conflict(s)`);
    new import_obsidian6.Notice(parts.length ? `Drive sync: ${parts.join(", ")}` : "Drive sync: everything up to date");
  }
  setStatus(text) {
    var _a;
    (_a = this.statusBar) == null ? void 0 : _a.setText(text);
  }
  async loadPluginData() {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const stored = await this.loadData();
    this.data = {
      settings: { ...DEFAULT_SETTINGS, ...(_a = stored == null ? void 0 : stored.settings) != null ? _a : {} },
      tokens: (_b = stored == null ? void 0 : stored.tokens) != null ? _b : null,
      state: (_c = stored == null ? void 0 : stored.state) != null ? _c : {},
      baseFolderId: (_d = stored == null ? void 0 : stored.baseFolderId) != null ? _d : null,
      vaultId: (_e = stored == null ? void 0 : stored.vaultId) != null ? _e : null,
      encryptionSalt: (_f = stored == null ? void 0 : stored.encryptionSalt) != null ? _f : null,
      changesPageToken: (_g = stored == null ? void 0 : stored.changesPageToken) != null ? _g : null,
      folderIds: (_h = stored == null ? void 0 : stored.folderIds) != null ? _h : {}
    };
  }
  async savePluginData() {
    await this.saveData(this.data);
  }
};
